## Fancy indexing and index tricks

#### Indexing with Arrays of Indices

In [1]:
import numpy as np

In [2]:
a = np.arange(12) ** 2
i = np.array([1, 1, 3, 8, 5])
a

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121],
      dtype=int32)

In [3]:
a[i]

array([ 1,  1,  9, 64, 25], dtype=int32)

In [4]:
j = np.array([[3, 4], [9, 7]])

In [5]:
a[j]

array([[ 9, 16],
       [81, 49]], dtype=int32)

When the indexed array a is multidimensional, a single array of indices refers to the first dimension of a

In [6]:
palette = np.array( [ [0,0,0],                # black
                       [255,0,0],              # red
                       [0,255,0],              # green
                       [0,0,255],              # blue
                       [255,255,255] ] )       # white
image = np.array([1, 2])
palette[image]

array([[255,   0,   0],
       [  0, 255,   0]])

In [7]:
image = np.array([[1, 2], [0, -1]])
palette[image]

array([[[255,   0,   0],
        [  0, 255,   0]],

       [[  0,   0,   0],
        [255, 255, 255]]])

We can also give indexes for more than one dimension. The arrays of indices for each dimension must have the same shape.

In [8]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [10]:
i = np.array([[1, 0],
              [2, 1]])
a[i]

array([[[ 4,  5,  6,  7],
        [ 0,  1,  2,  3]],

       [[ 8,  9, 10, 11],
        [ 4,  5,  6,  7]]])

In [12]:
j = np.array([[2, 3],
              [0, 3]])
a[i,j]

array([[6, 3],
       [8, 7]])

In [13]:
a[i, 2]

array([[ 6,  2],
       [10,  6]])

In [14]:
ii = np.array([1, 2])
a[i, ii]

array([[5, 2],
       [9, 6]])

In [15]:
a[:, j]

array([[[ 2,  3],
        [ 0,  3]],

       [[ 6,  7],
        [ 4,  7]],

       [[10, 11],
        [ 8, 11]]])

# ...

#### Indexing with Boolean Arrays

 use boolean arrays that have the same shape as the original array

In [18]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [17]:
b = a > 4
b

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]])

In [19]:
a[b]

array([ 5,  6,  7,  8,  9, 10, 11])

In [20]:
a[b] = 0
a

array([[0, 1, 2, 3],
       [4, 0, 0, 0],
       [0, 0, 0, 0]])

 for each dimension of the array we give a 1D boolean array selecting the slices we want

#### Indexing with strings

## Linear Algebra