#### basic operation

算术操作符是元素对元素的

In [1]:
import numpy as np

In [2]:
a = np.array([10,20,30,40])
b = np.arange(4)
b

array([0, 1, 2, 3])

In [3]:
a + b

array([10, 21, 32, 43])

In [4]:
a - b

array([10, 19, 28, 37])

In [5]:
a ** b

array([    1,    20,   900, 64000], dtype=int32)

In [6]:
a * 2

array([20, 40, 60, 80])

In [7]:
b > 3

array([False, False, False, False])

In [8]:
b > 2

array([False, False, False,  True])

In [9]:
np.sin(a)

array([-0.54402111,  0.91294525, -0.98803162,  0.74511316])

\* 操作符是元素对元素的，矩阵乘法可以用dot函数或方法

In [10]:
A = np.array([[1, 1],
             [0, 1]])
B = np.array([[2, 0],
             [3, 4]])
A * B

array([[2, 0],
       [0, 4]])

In [11]:
A.dot(B)

array([[5, 4],
       [3, 4]])

In [12]:
np.dot(A, B)

array([[5, 4],
       [3, 4]])

In [13]:
np.dot(B, A)

array([[2, 2],
       [3, 7]])

In [14]:
a = np.ones((2,3), dtype=int)
b = np.random.random((2,3))

In [15]:
a

array([[1, 1, 1],
       [1, 1, 1]])

In [16]:
b

array([[0.51974528, 0.06539748, 0.79255925],
       [0.62640832, 0.94864947, 0.2626559 ]])

In [17]:
a *= 3

In [18]:
a

array([[3, 3, 3],
       [3, 3, 3]])

In [19]:
b += a

In [20]:
b

array([[3.51974528, 3.06539748, 3.79255925],
       [3.62640832, 3.94864947, 3.2626559 ]])

When operating with arrays of different types, the type of the resulting array corresponds to the more general or precise one (a behavior known as upcasting)

In [21]:
# a = np.ones(3, dtype='int32')
a = np.ones(3, dtype=np.int32)
# a.dtype.name
b = np.linspace(0, np.pi, 3)
b.dtype.name

'float64'

In [22]:
c = a + b
c.dtype.name

'float64'

In [23]:
d = np.exp(c*1j)
d

array([ 0.54030231+0.84147098j, -0.84147098+0.54030231j,
       -0.54030231-0.84147098j])

In [24]:
d.dtype

dtype('complex128')

In [25]:
d.itemsize

16

Many unary operations, such as computing the sum of all the elements in the array, are implemented as methods of the ndarray class.

In [26]:
a = np.random.random((2,3))
a

array([[0.74334009, 0.02164691, 0.37599959],
       [0.00457424, 0.75863356, 0.23844974]])

In [27]:
a.sum()

2.1426441241082435

In [28]:
a.min()

0.004574235308159147

In [29]:
a.max()

0.7586335550760591

By default, these operations apply to the array as though it were a list of numbers, regardless of its shape. However, by specifying the axis parameter you can apply an operation along the specified axis of an array:

In [30]:
a = np.arange(12).reshape((3,4))
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [31]:
a.sum(axis=0)

array([12, 15, 18, 21])

#### Universal Functions

#### Indexing, Slicing and Iterating

一维

In [32]:
a = np.arange(10) ** 3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [33]:
a[1]

1

In [34]:
a[:]

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [35]:
a[1:3]

array([1, 8], dtype=int32)

In [36]:
a[:8]

array([  0,   1,   8,  27,  64, 125, 216, 343], dtype=int32)

In [37]:
a[:8:2]

array([  0,   8,  64, 216], dtype=int32)

In [38]:
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [39]:
a[8:2]

array([], dtype=int32)

In [40]:
a[8:2:-1]

array([512, 343, 216, 125,  64,  27], dtype=int32)

In [41]:
a[::-1]

array([729, 512, 343, 216, 125,  64,  27,   8,   1,   0], dtype=int32)

In [42]:
a[1:3] = 99

In [43]:
a

array([  0,  99,  99,  27,  64, 125, 216, 343, 512, 729], dtype=int32)

In [44]:
for i in a:
    print(i)

0
99
99
27
64
125
216
343
512
729


In [45]:
a = (x**2 for x in [1 ,2, 3])

In [46]:
type(a)

generator

In [47]:
for i in (x ** 3 for x in [1, 2, 3]):
    print(i)

1
8
27


多维，注意多维数组索引与python的区别

In [48]:
a = [[1,2],[3,4]]

In [49]:
a[0][1]

2

In [50]:
a[0,1]

TypeError: list indices must be integers or slices, not tuple

In [ ]:
def f(x, y):
    return (x+1)*(y+1)
a = np.fromfunction(f, (9, 9))
a

In [ ]:
def f(x, y):
#     print(type(x))
    return 10*x + y
a = np.fromfunction(f, (5,4))
a

In [ ]:
a[1,2]

In [ ]:
a[1:3]

In [ ]:
a[1:3,2]

When fewer indices are provided than the number of axes, the missing indices are considered complete slices:

In [ ]:
a[-2]

The expression within brackets in b[i] is treated as an i followed by as many instances of : as needed to represent the remaining axes. NumPy also allows you to write this using dots as b[i,...].

The dots (...) represent as many colons as needed to produce a complete indexing tuple. For example, if x is an array with 5 axes, then

In [ ]:
c = np.array( [[[  0,  1,  2],               # a 3D array (two stacked 2D arrays)
                 [ 10, 12, 13]],
                [[100,101,102],
                [110,112,113]]])
c

In [ ]:
c.shape

In [ ]:
c[1,...]

In [ ]:
c[...,1]

#### 迭代

In [ ]:
c


In [ ]:
for i in c:
    print(i)

In [ ]:
for i in c.flat:
    print(i)

##  Shape Manipulation


In [ ]:
a = np.floor(10*np.random.random((3,4)))
a

In [ ]:
a.ravel()

In [ ]:
a.reshape(6, 2)

In [ ]:
a.T

In [ ]:
a.reshape(2,-1)

#### Stacking together different arrays

In [ ]:
a = np.floor(10*np.random.random((2,2)))
a

In [ ]:
b = np.floor(10*np.random.random((2,2)))
b

In [ ]:
np.vstack((a,b))

In [ ]:
np.hstack((a,b))

In [76]:
a = np.array([np.arange(24).reshape(2,4,3) for _ in range(2)])
a

array([[[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11]],

        [[12, 13, 14],
         [15, 16, 17],
         [18, 19, 20],
         [21, 22, 23]]],


       [[[ 0,  1,  2],
         [ 3,  4,  5],
         [ 6,  7,  8],
         [ 9, 10, 11]],

        [[12, 13, 14],
         [15, 16, 17],
         [18, 19, 20],
         [21, 22, 23]]]])

In [78]:
np.stack(a, axis=3)

array([[[[ 0,  0],
         [ 1,  1],
         [ 2,  2]],

        [[ 3,  3],
         [ 4,  4],
         [ 5,  5]],

        [[ 6,  6],
         [ 7,  7],
         [ 8,  8]],

        [[ 9,  9],
         [10, 10],
         [11, 11]]],


       [[[12, 12],
         [13, 13],
         [14, 14]],

        [[15, 15],
         [16, 16],
         [17, 17]],

        [[18, 18],
         [19, 19],
         [20, 20]],

        [[21, 21],
         [22, 22],
         [23, 23]]]])

In [87]:
a = np.array([1,2,3])
a.shape

(3,)

## Copies and Views

#### No Copy at All

Simple assignments make no copy of array objects or of their data.

In [91]:
a = np.arange(12)
b = a
b is a

True

In [92]:
b.shape = (3,4)

In [93]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

Python passes mutable objects as references, so function calls make no copy.

In [94]:
id(a)

199592920

In [95]:
def f(x):
    print(id(x))
f(a)

199592920


#### View or Shallow Copy

Different array objects can share the same data. The view method creates a new array object that looks at the same data.

In [96]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [98]:
a.flags.owndata

True

In [100]:
a.base is a

False

In [101]:
b = a.view()

In [102]:
b.base is a

True

In [103]:
b.flags.owndata

False

In [108]:
b.shape = (2, 6)

In [109]:
b.shape

(2, 6)

In [110]:
a.shape

(3, 4)

In [111]:
b[0, 0] = 99
b

array([[99,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [112]:
a

array([[99,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

Slicing an array returns a view of it:

In [115]:
c = a[1:,1:3]
c

array([[ 5,  6],
       [ 9, 10]])

In [116]:
c[:,:] = 10000
c

array([[10000, 10000],
       [10000, 10000]])

In [117]:
a

array([[   99,     1,     2,     3],
       [    4, 10000, 10000,     7],
       [    8, 10000, 10000,    11]])

Deep Copy

In [118]:
d = a.copy()
d

array([[   99,     1,     2,     3],
       [    4, 10000, 10000,     7],
       [    8, 10000, 10000,    11]])

In [119]:
d.flags.owndata

True

In [120]:
d.base is a

False

In [121]:
d[-1, -1] = -99
d

array([[   99,     1,     2,     3],
       [    4, 10000, 10000,     7],
       [    8, 10000, 10000,   -99]])

In [122]:
a

array([[   99,     1,     2,     3],
       [    4, 10000, 10000,     7],
       [    8, 10000, 10000,    11]])