In [1]:
import numpy as np
import pandas as pd

In [2]:
index = pd.date_range('1/1/2000', periods=8)

In [3]:
s = pd.Series(np.random.randn(5), index=['a', 'b', 'c', 'd', 'e'])

In [4]:
df = pd.DataFrame(np.random.randn(8, 3), index=index,
                  columns=['A', 'B', 'C'])

In [5]:
wp = pd.Panel(np.random.randn(2, 5, 4), items=['Item1', 'Item2'],
              major_axis=pd.date_range('1/1/2000', periods=5),
              minor_axis=['A', 'B', 'C', 'D'])

## Head and Tail

## Attributes and the raw ndarray(s)

In [6]:
df.shape

(8, 3)

In [7]:
df.index

DatetimeIndex(['2000-01-01', '2000-01-02', '2000-01-03', '2000-01-04',
               '2000-01-05', '2000-01-06', '2000-01-07', '2000-01-08'],
              dtype='datetime64[ns]', freq='D')

In [8]:
df.columns

Index(['A', 'B', 'C'], dtype='object')

these attributes can be safely assigned to

In [9]:
df[:2]

A         B         C
2000-01-01  0.458861 -0.359051 -0.394386
2000-01-02 -0.811304  0.638485  0.077923

In [21]:
df.columns = [i.lower() for i in df.columns]

df

a         b         c
2000-01-01  0.458861 -0.359051 -0.394386
2000-01-02 -0.811304  0.638485  0.077923
2000-01-03  0.766771 -0.077005 -0.342291
2000-01-04 -1.285636  0.278375 -0.209117
2000-01-05 -0.948549 -0.117646  0.626161
2000-01-06  1.030917 -0.866556 -0.214995
2000-01-07  0.453816 -2.049419  1.188210
2000-01-08  0.246112  0.407338  0.816037

In [22]:
s.values

array([ 0.41750953, -0.47064956, -0.79283674, -1.58920555, -0.21793721])

In [23]:
df.values

array([[ 0.45886096, -0.35905084, -0.39438588],
       [-0.81130385,  0.63848541,  0.07792344],
       [ 0.76677126, -0.07700476, -0.34229056],
       [-1.28563579,  0.27837487, -0.20911687],
       [-0.94854872, -0.11764597,  0.62616104],
       [ 1.03091655, -0.86655603, -0.21499477],
       [ 0.45381572, -2.04941888,  1.18820961],
       [ 0.24611245,  0.40733821,  0.81603655]])

In [24]:
wp.values

array([[[ 0.05255753,  0.59977842,  0.07918507, -0.42786923],
        [-1.79511585, -0.6793234 , -1.01822807,  0.65515943],
        [-0.86167749,  1.08671699, -0.40982301,  0.57305271],
        [ 0.94799355,  0.1088867 , -0.72891324,  0.21569616],
        [-1.3603524 , -2.31355522, -0.76545808, -0.13607833]],

       [[-0.22505223,  2.07560111, -0.33351203,  1.31724101],
        [-0.75376578,  1.24509273, -1.72980412, -1.83045079],
        [ 0.45183432,  2.22057722, -0.8574622 , -1.04380529],
        [-0.69488236,  2.92186076,  0.86390985, -0.2411446 ],
        [ 2.1772522 ,  1.63719956,  0.93748641,  0.1898863 ]]])